# Generated by Django 5.2 on 2025-05-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
